import { useMemo, useState } from 'react';
import { AppHeader } from '../components/AppHeader.js';
import { AppState } from '../components/AppState.js';
import { Chart } from '../components/Chart.js';
import { getAccount, getHistory, getSnapshot } from '../fixtures/snapshot.js';
import type { PageId } from '../preview/routes.js';
import { usePreview } from '../preview/PreviewContext.js';

type Go = (page: PageId, query?: Record<string, string>) => void;
const snapshot = getSnapshot();
const account = getAccount();
const history = getHistory();

function Shell({ title, eyebrow, back = true, children, go }: { title: string; eyebrow: string; back?: boolean; children: React.ReactNode; go: Go }) {
  return <><AppHeader title={title} eyebrow={eyebrow} back={back} onBack={() => historyBack(go)} /><main className="page-content">{children}</main></>;
}
function historyBack(go: Go) { if (window.history.length > 1) window.history.back(); else go('home'); }
const Button = ({ children, onClick, kind = 'primary', disabled = false }: { children: React.ReactNode; onClick?: () => void; kind?: string; disabled?: boolean }) => <button type="button" className={`btn ${kind}`} onClick={onClick} disabled={disabled}>{children}</button>;
const Note = ({ children }: { children: React.ReactNode }) => <div className="note">{children}</div>;
const Card = ({ children, accent = '' }: { children: React.ReactNode; accent?: string }) => <section className={`card ${accent}`}>{children}</section>;

export function WelcomePage({ go }: { go: Go }) {
  const { state, dispatch } = usePreview();
  return <Shell title="光与回声" eyebrow="MUSICMIRROR / 你的音乐镜像" back={false} go={go}>
    <Chart chart={{ kind: 'prism' }} /><p className="subtitle">观察长期反复聆听什么，最近主动选择什么，以及它们如何相遇。</p>
    <Card><h2>先说清楚，再开始</h2><p>这里只使用固定合成数据。浏览器 Preview 不会连接真实网易云账号。</p></Card>
    <div className="actions"><Button onClick={() => go('login')}>开始连接</Button><Button kind="secondary" onClick={() => { dispatch({ type: 'LOGIN', account }); dispatch({ type: 'SET_BOUND', bound: true }); go('home'); }}>先看演示</Button>{state.authenticated && <Button kind="link" onClick={() => go('home')}>继续查看我的镜像</Button>}</div>
  </Shell>;
}

export function LoginPage({ go }: { go: Go }) {
  const { state, dispatch } = usePreview(); const scenario = state.scenarioId;
  const waiting = scenario.includes('waiting') || scenario.includes('scanned');
  return <Shell title="连接网易云" eyebrow="CONNECT / 授权由你决定" go={go}>
    <Note>演示二维码不可扫描，也不会发送任何凭证。</Note>
    <Card><div className={`fake-qr ${waiting ? '' : 'muted-qr'}`} aria-label="演示二维码不可扫描">演示二维码<br />不可扫描</div><h2>{scenario === 'qr-expired' ? '二维码已过期' : scenario === 'qr-scanned' ? '已扫码，等待确认' : waiting ? '等待扫码' : '准备生成二维码'}</h2><p className="muted">请用网易云 App 完成确认；这里仅模拟流程。</p></Card>
    <div className="actions"><Button onClick={() => dispatch({ type: 'SCENARIO', scenarioId: waiting ? 'qr-authenticated' : 'qr-waiting' })}>{waiting ? '模拟确认' : '生成演示二维码'}</Button><Button kind="secondary" onClick={() => { dispatch({ type: 'LOGIN', account }); dispatch({ type: 'SET_BOUND', bound: true }); go('inputs'); }}>直接进入演示账号</Button></div>
  </Shell>;
}

export function HomePage({ go }: { go: Go }) {
  const { state, dispatch } = usePreview(); const status = ['loading','error','empty'].includes(state.scenarioId) ? state.scenarioId as 'loading'|'error'|'empty' : 'ready';
  return <Shell title="我的音乐审美" eyebrow="MUSICMIRROR / 我的镜像" back={false} go={go}><span className="badge">演示账号 · 合成数据</span>
    <AppState state={status} actionLabel={status === 'error' ? '重新查看' : status === 'empty' ? '配置输入并分析' : undefined} onAction={() => status === 'empty' ? go('inputs') : dispatch({ type: 'SCENARIO', scenarioId: 'ready' })}>
      <p className="caption">采集于 {snapshot.createdAt}<br />{snapshot.algorithmVersion}</p><Card><Chart chart={{kind:'prism'}}/><h2>长期行为 × 主动选择</h2><div className="grid"><div><strong className="big">100</strong><small>长期样本 / 次数加权</small></div><div><strong className="big">37</strong><small>选定红心 / 歌曲等权</small></div></div><p className="caption">用户提供的红心时间</p></Card>
      <Card accent="accent"><h2>反复聆听形成稳定中心</h2></Card><Card accent="cyan"><h2>主动选择仍保留探索空间</h2></Card>
      <div className="actions"><Button onClick={() => go('explore')}>探索全部审美卡片</Button><Button kind="secondary" onClick={() => go('inputs')}>管理两类输入</Button><Button kind="secondary" onClick={() => go('run')}>刷新我的镜像</Button></div>
    </AppState></Shell>;
}

export function ExplorePage({ go }: { go: Go }) {
  const { state, dispatch } = usePreview(); const mode = ['long','heart'].includes(state.scenarioId) ? state.scenarioId : 'cards';
  return <Shell title="看看偏好如何相遇" eyebrow="EXPLORE / 线索与共性" back={false} go={go}><div className="tabs">{[['cards','12张卡片'],['long','长期结构'],['heart','主动偏好']].map(([id,label])=><button className={mode===id?'selected':''} key={id} onClick={()=>dispatch({type:'SCENARIO',scenarioId:id})}>{label}</button>)}</div>
    {mode === 'cards' ? snapshot.cards.map(c=><Card key={c.id}><span className="badge">{c.base.statusText} · 覆盖 {c.base.coverageText}</span><button className="card-link" onClick={()=>go('card',{id:c.id})}><h2>{c.title} ›</h2><p>{c.base.summaries[0]?.text || c.purpose}</p></button></Card>) : <><Note>{mode==='long'?'长期 Top100 · 播放次数加权':'选定红心 · 每首歌曲等权'}</Note><Card><Chart chart={mode==='long'?snapshot.modules.longTermListening.chart:snapshot.modules.recentFavorites.chart}/></Card></>}
  </Shell>;
}

export function StructurePage({ go }: { go: Go }) { return <Shell title="我的长期结构" eyebrow="LONG TERM / 反复出现的选择" go={go}><Note>长期 Top100 · 播放次数加权。未进入 Top100 不等于从未听过。</Note><Card><Chart chart={snapshot.modules.longTermListening.chart}/>{snapshot.modules.longTermListening.stats.map(x=><div className="row" key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}</Card></Shell>; }
export function PreferencesPage({ go }: { go: Go }) { const {state}=usePreview(); return <Shell title="我的主动偏好" eyebrow="RED HEART / 由你选定" go={go}>{state.scenarioId==='unavailable'?<AppState state="empty" title="红心模块尚未配置" message="选定想观察的红心歌曲后再分析。" actionLabel="配置输入" onAction={()=>go('inputs')}/>:<><Note>{snapshot.modules.recentFavorites.timeWindowLabel} · 每首歌曲等权</Note><Card><Chart chart={snapshot.modules.recentFavorites.chart}/>{snapshot.modules.recentFavorites.songs.map(x=><div className="row" key={x.id}><span>{x.name}</span><small>{x.likedAt ?? '时间未知'}</small></div>)}</Card></>}</Shell>; }

export function HistoryPage({ go }: { go: Go }) { const {state,dispatch}=usePreview(); const count=state.scenarioId==='none'?0:state.scenarioId==='single'?1:history.length; const [selected,setSelected]=useState<string[]>([]); return <Shell title="你的审美，有了时间轴" eyebrow="HISTORY / 留住每一次镜像" back={false} go={go}><Button kind="secondary" onClick={()=>go('trends')}>查看持续变化 →</Button>{count===0?<AppState state="empty" title="还没有保存的镜像" actionLabel="开始配置输入" onAction={()=>go('inputs')}/>:history.slice(0,count).map(item=><Card key={item.snapshotId}><label className="checkline"><input type="checkbox" checked={selected.includes(item.snapshotId)} onChange={e=>setSelected(e.target.checked?[...selected,item.snapshotId]:selected.filter(x=>x!==item.snapshotId))}/><span>{item.createdAt}</span></label><p className="caption">{item.version}<br />{item.note}</p><Button kind="link" onClick={()=>go('evidence',{snapshotId:item.snapshotId})}>查看当时的报告 →</Button></Card>)}{count>0&&<Button onClick={()=>selected.length===2?go('compare',{from:selected[0],to:selected[1]}):dispatch({type:'TOAST',message:'请选择两份报告',tone:'danger'})}>比较选中的 {selected.length} 份报告</Button>}</Shell>; }

export function CardPage({ go }: { go: Go }) { const {state,dispatch}=usePreview(); const found=snapshot.cards.find(c=>c.id===(state.query.id||'center'))||snapshot.cards[0]; const enhanced=state.scenarioId==='enhanced'||state.scenarioId==='unavailable'; const variant=enhanced?(found.enhanced||found.base):found.base; return <Shell title={found.title} eyebrow="AESTHETIC CARD / 可验证的线索" go={go}><div className="tabs"><button className={!enhanced?'selected':''} onClick={()=>dispatch({type:'SCENARIO',scenarioId:'base'})}>现有数据</button><button className={enhanced?'selected':''} onClick={()=>dispatch({type:'SCENARIO',scenarioId:'enhanced'})}>增强分析</button></div><span className="badge">{variant.statusText} · 覆盖 {variant.coverageText}</span>{variant.status==='unavailable'?<AppState state="empty" title="增强分析需要更多资料" message={variant.requiredData.join('、')||'完整播放事件与验证后的声音轴'}/>:<Card><Chart chart={variant.chart}/>{variant.summaries.map(x=><p key={x.text}>{x.text}</p>)}</Card>}<Button kind="secondary" onClick={()=>go('evidence',{id:found.id,variant:enhanced?'enhanced':'base'})}>查看事实与计算依据</Button></Shell>; }

export function EvidencePage({ go }: { go: Go }) { const card=snapshot.cards[0]; return <Shell title="每一句，都有依据" eyebrow="EVIDENCE / 事实与来源" go={go}><Note>{snapshot.algorithmVersion} · {snapshot.createdAt}<br />100 首长期 / 37 首选定红心</Note><Card><h2>如何计算</h2><p>{card.base.method}</p>{card.base.limitations.map(x=><div className="rule" key={x}>{x}</div>)}</Card><Card><h2>事实明细</h2>{card.base.facts.map(x=><div className="row" key={x.label}><small>{x.label}</small><span>{x.value}</span></div>)}</Card><div className="actions"><Button kind="secondary" onClick={()=>go('share')}>生成分享图片</Button><Button kind="secondary" onClick={()=>go('export')}>导出本次报告</Button></div></Shell>; }
export function ComparePage({ go }: { go: Go }) { const {state}=usePreview(); const bad=state.scenarioId==='incompatible'; return <Shell title="两次选择，具体差在哪里" eyebrow="COMPARE / 冻结报告对照" go={go}>{bad?<AppState state="empty" title="这两份报告口径不同" message="算法版本或选择规则不同，不能生成差值。"/>:<><Note>两份报告使用相同算法与输入规则，可以比较。</Note><Card><h2>长期中心更集中</h2><div className="grid"><strong className="big">29.4%</strong><strong className="big">32.9%</strong></div><p className="caption">只描述可验证差异，不判断品味高低。</p></Card></>}</Shell>; }
export function TrendsPage({ go }: { go: Go }) { const {state}=usePreview(); const enough=state.scenarioId!=='insufficient'; return <Shell title="一份持续变化的自画像" eyebrow="TRENDS / 三次以上才描述趋势" go={go}>{enough?<><Note>3 次同版本、同规则观察</Note><Card><div className="trend-line" aria-label="三次观察趋势">●────●────●</div><h2>整体稳定，最近一次轻微变化</h2><p>方向仅表示份额变化，不表示审美进步或退步。</p></Card></>:<AppState state="empty" title="再多一次，才描述趋势" message="至少需要三次同版本、同规则的可比观察。"/>}</Shell>; }

export function InputsPage({ go }: { go: Go }) { const {state,dispatch}=usePreview(); const [value,setValue]=useState(''); const [items,setItems]=useState(state.scenarioId==='empty'?[]:snapshot.modules.recentFavorites.songs); const add=()=>{const id=value.trim();if(!id)return;if(items.some(x=>x.id===id)){dispatch({type:'TOAST',message:'这首歌已经在列表中'});return;}if(items.length>=50){dispatch({type:'TOAST',message:'最多选择 50 首',tone:'danger'});return;}setItems([...items,{id,name:`示例歌曲 ${id}`,likedAt:null}]);setValue('');}; return <Shell title="选择你的红心歌曲" eyebrow="INPUT 02 / 主动选择" go={go}><Note>最多 50 首，每首歌曲等权。这里不会把最近播放当作红心。</Note><Card><label className="field">歌曲 ID<input value={value} onChange={e=>setValue(e.target.value)} placeholder="例如 0421"/></label><Button kind="secondary" onClick={add}>添加</Button>{items.map(x=><div className="row" key={x.id}><span>{x.name}</span><button className="remove" aria-label={`删除 ${x.name}`} onClick={()=>setItems(items.filter(i=>i.id!==x.id))}>×</button></div>)}</Card><Button onClick={()=>{dispatch({type:'SAVE_INPUTS',items});go('run')}}>保存并准备分析</Button></Shell>; }
export function RunPage({ go }: { go: Go }) { const {state,dispatch}=usePreview(); const failed=state.scenarioId==='failed'; const done=state.scenarioId==='completed'; return <Shell title={failed?'这次没能完成分析':done?'镜像已经准备好':'正在整理音乐线索'} eyebrow="ANALYSIS / 可离开后恢复" go={go}>{failed?<AppState state="error" message="演示任务失败，没有生成新报告。" actionLabel="重试" onAction={()=>dispatch({type:'SCENARIO',scenarioId:'processing'})}/>:done?<><Card><h2>分析完成</h2><p>本次使用固定合成数据，没有覆盖历史镜像。</p></Card><Button onClick={()=>go('home')}>打开本次镜像</Button></>:<AppState state="loading" message="正在组合长期行为与主动选择。"><span/></AppState>} {!done&&!failed&&<Button kind="secondary" onClick={()=>dispatch({type:'SCENARIO',scenarioId:'completed'})}>模拟完成</Button>}</Shell>; }

export function AccountPage({ go }: { go: Go }) { const {state,dispatch}=usePreview(); const confirm=(title:string,message:string,action:()=>void)=>{if(window.confirm(`${title}\n\n${message}`))action()}; return <Shell title="音乐由你，资料也由你" eyebrow="YOUR MUSIC / YOUR DATA" back={false} go={go}><Card><h2>{account.nickname}</h2><span className="badge">{state.bound?'已连接':'已解绑，历史报告保留'}</span></Card><Card><h2>外观</h2><div className="tabs">{(['system','light','dark'] as const).map(x=><button key={x} className={state.themeChoice===x?'selected':''} onClick={()=>dispatch({type:'THEME',themeChoice:x})}>{x==='system'?'跟随系统':x==='light'?'浅色':'深色'}</button>)}</div></Card><Card><Button kind="link" onClick={()=>go('inputs')}>管理两类输入 ›</Button><Button kind="link" onClick={()=>go('privacy')}>隐私与数据生命周期 ›</Button><Button kind="link" onClick={()=>go('export')}>导出报告与输入 ›</Button><Button kind="link" onClick={()=>go('share')}>生成分享图片 ›</Button></Card><div className="actions"><Button kind="secondary" onClick={()=>confirm('解除网易云连接？','停止采集并移除授权；历史报告继续保留。',()=>dispatch({type:'SET_BOUND',bound:false}))}>解除连接</Button><Button kind="secondary" onClick={()=>confirm('退出当前登录？','绑定和报告保留，仅结束本次会话。',()=>{dispatch({type:'LOGOUT'});go('welcome')})}>退出登录</Button><Button kind="danger" onClick={()=>confirm('删除全部项目数据？','报告、输入、任务与会话将删除，无法撤回。',()=>{dispatch({type:'RESET'});go('welcome')})}>删除全部项目数据</Button></div></Shell>; }
export function PrivacyPage({ go }: { go: Go }) { return <Shell title="清楚知道，保存了什么" eyebrow="PRIVACY / 最小化与可撤回" go={go}><Card><h2>项目会保存</h2><div className="rule">冻结的分析报告与证据</div><div className="rule">你明确选择的红心输入</div><div className="rule">任务状态与当前项目会话</div></Card><Card><h2>项目不会导出</h2><p>网易云 Cookie、token 与账号 ID 不进入报告文件。</p></Card><Note>浏览器 Preview 仅使用 localStorage 保存演示状态。</Note></Shell>; }
export function SharePage({ go }: { go: Go }) { const {dispatch}=usePreview(); const [name,setName]=useState(false); const [songs,setSongs]=useState(false); const [made,setMade]=useState(false); return <Shell title="分享你愿意展示的部分" eyebrow="SHARE / 先预览，再保存" go={go}><Card><label className="checkline"><input type="checkbox" checked={name} onChange={e=>setName(e.target.checked)}/>显示昵称</label><label className="checkline"><input type="checkbox" checked={songs} onChange={e=>setSongs(e.target.checked)}/>显示代表歌曲</label></Card>{made&&<Card accent="dark"><span className="badge">合成数据</span><h2>我的音乐镜像</h2>{name&&<p>演示账号</p>}<strong className="big">100 × 37</strong>{songs&&<p>示例歌曲 0421 · 示例歌曲 1903</p>}</Card>}<Button onClick={()=>setMade(true)}>生成预览</Button>{made&&<Button kind="secondary" onClick={()=>dispatch({type:'TOAST',message:'已模拟保存图片'})}>模拟保存图片</Button>}</Shell>; }
export function ExportPage({ go }: { go: Go }) { const {dispatch}=usePreview(); const [format,setFormat]=useState('json'); const safe=useMemo(()=>JSON.stringify({snapshotId:snapshot.snapshotId,algorithmVersion:snapshot.algorithmVersion,modules:snapshot.modules},null,2),[]); const save=()=>{const blob=new Blob([format==='json'?safe:'songId,name\n0421,示例歌曲 0421'],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`musicmirror-demo.${format==='json'?'json':'csv'}`;a.click();URL.revokeObjectURL(a.href);dispatch({type:'TOAST',message:'演示文件已生成'});}; return <Shell title="把报告留在自己手中" eyebrow="EXPORT / 只导出演示资料" go={go}><Note>导出不含 Cookie、token、昵称或账号 ID。</Note><div className="tabs">{['json','input1','input2'].map(x=><button key={x} className={format===x?'selected':''} onClick={()=>setFormat(x)}>{x.toUpperCase()}</button>)}</div><Card><h2>{format==='json'?'完整报告 JSON':format==='input1'?'输入1 · 长期结构 CSV':'输入2 · 红心选择 CSV'}</h2><p>文件仅包含固定合成 fixture。</p></Card><Button onClick={save}>模拟下载文件</Button></Shell>; }

export function PageView({ page, go }: { page: PageId; go: Go }) {
  const map: Record<PageId, React.ComponentType<{go:Go}>> = { welcome:WelcomePage,login:LoginPage,home:HomePage,explore:ExplorePage,structure:StructurePage,preferences:PreferencesPage,history:HistoryPage,compare:ComparePage,trends:TrendsPage,card:CardPage,evidence:EvidencePage,share:SharePage,export:ExportPage,account:AccountPage,privacy:PrivacyPage,inputs:InputsPage,run:RunPage };
  const Component=map[page]; return <Component go={go}/>;
}
